import React, { useEffect, useMemo, useRef, useState } from "react";
import type { RefObject } from "react";
import { prepareFuzzySearch, sortSearchResults } from "obsidian";
import type { SearchResult } from "obsidian";
import { useT } from "./TranslatorContext";
import { suppressOwnTooltip } from "./tooltipSuppression";
import { isComposing } from "./keyboard";

/** A `/name`-command entry surfaced for autocomplete. */
export interface CommandEntry {
	name: string;
	description: string;
	kind: "template" | "skill" | "extension";
	/** Text inserted after `/`; differs only for a shadowed skill. */
	invocation: string;
}

interface CommandMenuProps {
	/** All available prompt templates and skills, in service-defined order. */
	commands: CommandEntry[];
	/** The text after the leading `/`, lowercased. Matching is case-insensitive regardless. */
	query: string;
	/**
	 * The listbox's id, generated by the composer — the same value its textarea
	 * names in `aria-controls`. The composer owns the id because the combobox
	 * wiring has to agree on it from both ends; the menu only wears it.
	 */
	menuId: string;
	/**
	 * Reports the highlighted option's id whenever it moves, and `null` when
	 * nothing is highlighted (no matches, or the menu going away). The composer
	 * mirrors that onto the textarea's `aria-activedescendant` — the one channel
	 * through which a screen reader hears the highlight — so the two attributes
	 * cannot drift apart. Option ids are derived from {@link CommandMenuProps.menuId},
	 * so the reported value is always one the composer can quote verbatim.
	 */
	onActiveChange?: (activeOptionId: string | null) => void;
	/**
	 * Called with the chosen entry. The composer inserts its invocation plus a
	 * trailing space so the user can keep typing arguments.
	 */
	onSelect: (command: CommandEntry) => void;
	/** Called when the user dismisses the menu (Escape or blur). */
	onClose: () => void;
	/**
	 * The composer's textarea, which this menu must never render without.
	 *
	 * The menu renders nothing while a query matches nothing, so on its own it
	 * has no element to ask which document its keys arrive on. The textarea is
	 * always there, always in the same document as the keys the user types, and
	 * this menu already leans on it for the combobox pattern — so it is the
	 * anchor for the keydown binding too.
	 */
	anchorRef: RefObject<HTMLTextAreaElement | null>;
}

/**
 * Autocomplete list for `/name` prompt templates and skills, floated above the composer.
 *
 * Keyboard-only by design: the composer opens it on `/`, and the arrow keys and
 * Enter it owns here are the ones that complete a command. Enter *completes*
 * rather than sends — a half-typed `/su` should not fire a prompt — so the
 * composer's send handler bails while this menu is open.
 *
 * The list fuzzy-matches Obsidian-style on the text after `/` — subsequence hits
 * like `/org` → `tag-organize` rank tighter matches first — rather than by
 * prefix, because hyphenated skill names would otherwise force users to recall
 * where a name starts instead of what it sounds like. With no matches it renders
 * nothing, which lets the composer treat `/unknown` as a normal (if invalid)
 * draft until the user sends it.
 *
 * It plays the option half of the ARIA combobox pattern: the composer's textarea
 * carries `role="combobox"` and quotes the highlighted option through
 * `aria-activedescendant`, which this menu keeps current via
 * {@link CommandMenuProps.onActiveChange}. The textarea is where focus lives —
 * the user is typing the command — so the ownership boundary is fixed by the
 * pattern, not by preference.
 */
export function CommandMenu({ commands, query, menuId, onActiveChange, onSelect, onClose, anchorRef }: CommandMenuProps): React.JSX.Element | null {
	const t = useT();
	const matches = useMemo(() => {
		if (!query) {
			// An empty query opens the full list in service order — no scoring needed.
			return commands;
		}
		const search = prepareFuzzySearch(query);
		const scored = commands
			.map((command) => ({ command, match: search(command.name) }))
			.filter((entry): entry is { command: CommandEntry; match: SearchResult } => entry.match !== null);
		sortSearchResults(scored);
		return scored.map((entry) => entry.command);
	}, [commands, query]);
	const [activeIndex, setActiveIndex] = useState(0);
	const listRef = useRef<HTMLUListElement | null>(null);
	/*
	 * The id of the highlighted option, in the combobox grammar. Guarded by the
	 * lookup rather than the index alone: for one render after the query narrows,
	 * `activeIndex` can still point past the (shorter) filtered set — the reset
	 * effect below has not run yet — and quoting a nonexistent id would leave
	 * `aria-activedescendant` dangling on exactly the frame a screen reader asks.
	 */
	const activeOptionId = matches[activeIndex] ? `${menuId}-option-${activeIndex}` : null;

	// Keep the highlight inside the filtered set as the query narrows.
	useEffect(() => {
		setActiveIndex(0);
	}, [matches.length]);

	// Mirror the highlight up to the composer's `aria-activedescendant`, and
	// clear it on the way out so the textarea never advertises a menu that left.
	const onActiveChangeRef = useRef(onActiveChange);
	onActiveChangeRef.current = onActiveChange;
	useEffect(() => {
		onActiveChangeRef.current?.(activeOptionId);
		return () => onActiveChangeRef.current?.(null);
	}, [activeOptionId]);

	// Scroll the highlighted row into view as the highlight moves.
	useEffect(() => {
		const list = listRef.current;
		if (!list) {
			return;
		}
		const item = list.children[activeIndex] as HTMLElement | undefined;
		item?.scrollIntoView({ block: "nearest" });
	}, [activeIndex]);

	/*
	 * The keydown handler reads live state through this ref, so the listener can
	 * be bound once per document and never churned on every keystroke. A
	 * re-binding effect would leave stale listeners on the document across test
	 * teardowns that do not unmount — and the ref is also the cheaper, correct
	 * shape: one listener, reading whatever the latest render wrote.
	 */
	const stateRef = useRef({ matches, activeIndex, onSelect, onClose });
	stateRef.current = { matches, activeIndex, onSelect, onClose };

	/*
	 * Which document the menu listens on: the one the composer's textarea lives
	 * in, asked per bind rather than read once from the module-global `document`
	 * — which is always the main window's, leaving a panel dragged into a popout
	 * window with a menu listening on a document its keys never reach. The
	 * textarea is the anchor because the menu itself renders nothing on a
	 * zero-match frame, and that frame still has to keep its Escape branch
	 * (below) working — a component with no DOM cannot answer the question alone.
	 *
	 * Bound once per document: the handler reads live state through `stateRef`,
	 * so a re-binding effect on every keystroke would only churn listeners
	 * (and strand stale ones across teardowns that do not unmount). The one
	 * event that re-binds is the window itself changing — see below.
	 */
	useEffect(() => {
		const handleKeyDown = (event: KeyboardEvent): void => {
			// An input method mid-composition owns the keyboard: Enter accepts the
			// candidate, Escape cancels it, and the arrows page the candidate list.
			// Completing a command on any of them hijacks the composition — the same
			// guard the send path applies, shared from `keyboard.ts`.
			if (isComposing(event)) {
				return;
			}
			const { matches: currentMatches, activeIndex: currentIndex, onSelect: currentOnSelect, onClose: currentOnClose } =
				stateRef.current;
			if (currentMatches.length === 0) {
				if (event.key === "Escape") {
					event.preventDefault();
					event.stopPropagation();
					currentOnClose();
				}
				return;
			}
			if (event.key === "ArrowDown") {
				event.preventDefault();
				event.stopPropagation();
				setActiveIndex((index) => (index + 1) % currentMatches.length);
				return;
			}
			if (event.key === "ArrowUp") {
				event.preventDefault();
				event.stopPropagation();
				setActiveIndex((index) => (index - 1 + currentMatches.length) % currentMatches.length);
				return;
			}
			// Plain Enter completes the highlighted command. A modifier chord
			// (⌘/Ctrl+Enter) is the send shortcut, and send is sacred: let it pass so
			// the composer's own listener can fire it. Completing on ⌘↵ would swallow
			// a send the user clearly asked for.
			if (event.key === "Enter" && !event.metaKey && !event.ctrlKey && !event.altKey) {
				event.preventDefault();
				event.stopPropagation();
				const match = currentMatches[currentIndex];
				if (match) {
					currentOnSelect(match);
				}
				return;
			}
			if (event.key === "Escape") {
				event.preventDefault();
				event.stopPropagation();
				currentOnClose();
			}
		};

		// Capture phase, ahead of the composer's own send handler, so Enter here
		// never reaches send.
		const anchor = anchorRef.current;
		if (!anchor) {
			return;
		}
		let doc = anchor.ownerDocument;
		doc.addEventListener("keydown", handleKeyDown, { capture: true });
		// Dragging the leaf to another window moves the DOM without remounting
		// React, so the document the keys land on changes underneath this
		// listener; re-hang on the element's own migration announcement.
		// Optional call because happy-dom's elements carry no Obsidian
		// augmentation — under `bun test` there is no announcement, and the
		// binding simply lives until the effect tears down.
		const unwatchMigration = anchor.onWindowMigrated?.((win) => {
			// Removed from the document it was bound to — `doc`, not a fresh read of
			// `anchor.ownerDocument`, which is the other document by now and would
			// strand the old listener.
			doc.removeEventListener("keydown", handleKeyDown, { capture: true });
			doc = win.document;
			doc.addEventListener("keydown", handleKeyDown, { capture: true });
		});
		return () => {
			doc.removeEventListener("keydown", handleKeyDown, { capture: true });
			unwatchMigration?.();
		};
	}, [anchorRef]);

	if (matches.length === 0) {
		return null;
	}

	return (
		<ul
			ref={listRef}
			id={menuId}
			className="piem-chat__command-menu"
			role="listbox"
			aria-label={t.t("chat.commandMenuAria")}
			onMouseOver={suppressOwnTooltip}
		>
			{matches.map((match, index) => (
				<li
					key={`${match.kind}:${match.name}`}
					id={`${menuId}-option-${index}`}
					role="option"
					aria-selected={index === activeIndex}
					className="piem-chat__command-menu-item"
				>
					{/*
					 * One row, three spans, in the order they are read as well as the order
					 * they are seen: name, what it does, which sort it is. No wrapper around
					 * the first and last — the row itself is the flex line now, and the
					 * `<span>` that used to pair name with kind only existed to hold them on
					 * a line above the description.
					 *
					 * Nothing here reorders in CSS. The trailing kind sits last in the DOM
					 * too, so a screen reader's reading order and the visual left-to-right
					 * cannot disagree.
					 */}
					<button
						type="button"
						className="piem-chat__command-menu-button"
						onMouseEnter={() => setActiveIndex(index)}
						onClick={() => onSelect(match)}
						tabIndex={-1}
					>
						<span className="piem-chat__command-menu-name">/{match.name}</span>
						{match.description ? <span className="piem-chat__command-menu-desc">{match.description}</span> : null}
						<span className="piem-chat__command-menu-kind">
							{t.t(match.kind === "template" ? "chat.commandKindTemplate" : match.kind === "skill" ? "chat.commandKindSkill" : "chat.commandKindExtension")}
						</span>
					</button>
				</li>
			))}
		</ul>
	);
}
